# Generated by Django 3.0.4 on 2020-04-10 17:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('shop_key', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('slug', models.CharField(default=1, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Shops',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=10)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 4, 10, 22, 47, 33, 445379), verbose_name='Added_Date')),
                ('slug', models.CharField(default=1, max_length=200)),
                ('item_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Shop')),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
    ]
